# Generated by Django 5.0.3 on 2024-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedproperty',
            constraint=models.UniqueConstraint(models.F('account'), models.F('property_id'), name='account-property_id'),
        ),
    ]
