# Generated by Django 5.0.3 on 2024-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_savedproperty_account_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='property_id',
            field=models.CharField(max_length=100),
        ),
    ]
