# Generated by Django 5.0.6 on 2024-06-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapRateFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_tax_rate', models.DecimalField(decimal_places=4, default=0.0091, max_digits=5)),
                ('mgmt_fee_rate', models.DecimalField(decimal_places=4, default=0.0091, max_digits=5)),
                ('insurance', models.IntegerField(default=136)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
