# Generated by Django 5.0.6 on 2024-06-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_insurance_caprateformula_mo_insurance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caprateformula',
            old_name='property_tax_rate',
            new_name='annual_property_tax_rate',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_hoa',
            new_name='monthly_hoa_fee',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_insurance',
            new_name='monthly_insurance',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_leasing_fee',
            new_name='monthly_leasing_fee',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_maintance_as_rate',
            new_name='monthly_maintance_as_rate',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_mgmt_fee_rate',
            new_name='monthly_management_fee_rate',
        ),
        migrations.RenameField(
            model_name='caprateformula',
            old_name='mo_utilities',
            new_name='monthly_utilities',
        ),
    ]
