# Generated by Django 5.0.3 on 2024-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='address',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
