# Generated by Django 5.0.6 on 2024-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_property_tax_rate_caprateformula_annual_property_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_maintance_as_rate',
            field=models.DecimalField(decimal_places=2, default=0.08, max_digits=3),
        ),
    ]
