# Generated by Django 5.0.3 on 2024-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_savedproperty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-03 20:31'),
            preserve_default=False,
        ),
    ]
