# Generated by Django 5.0.6 on 2024-06-10 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_caprateformula_monthly_maintance_as_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprateformula',
            name='annual_property_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0091, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_hoa_fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_insurance',
            field=models.IntegerField(default=136, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_leasing_fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_maintance_as_rate',
            field=models.DecimalField(decimal_places=2, default=0.08, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_management_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.0091, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_utilities',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
