# Generated by Django 5.0.3 on 2024-04-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_savedproperty_image_savedproperty_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
