# Generated by Django 5.0.3 on 2024-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_savedproperty_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='image',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
