# Generated by Django 5.0.6 on 2024-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_caprateformula_annual_property_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprateformula',
            name='annual_property_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0091, max_digits=5),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_hoa_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_insurance',
            field=models.PositiveIntegerField(default=136),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_leasing_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_maintance_as_rate',
            field=models.DecimalField(decimal_places=2, default=0.08, max_digits=3),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_management_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.0091, max_digits=5),
        ),
        migrations.AlterField(
            model_name='caprateformula',
            name='monthly_utilities',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
