# Generated by Django 5.0.4 on 2024-04-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='SavedProperty',
        ),
    ]
