# Generated by Django 5.0.4 on 2024-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_blockeduser_blockeduser_profile_blocked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('Searching for Investment Property', 'Searching for Investment Property'), ('Searching for New Home', 'Searching for New Home'), ('Moving Soon', 'Moving Soon'), ('Just Browsing', 'Just Browsing'), ('Other', 'Other')], default='Searching for Investment Property', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
