# Generated by Django 5.0.6 on 2024-06-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_goal_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_search',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
