# Generated by Django 5.0.6 on 2024-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_profile_last_search_usersearches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='dark', max_length=100),
        ),
    ]
