# Generated by Django 5.0.4 on 2024-05-14 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentprofile_delete_agent_lead_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(models.F('agent'), models.F('lead'), name='agent-lead'),
        ),
    ]
