# Generated by Django 5.0.4 on 2024-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_lead_options_lead_agent_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0),
        ),
    ]
