# Generated by Django 5.0.4 on 2024-05-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentcontactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontactform',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
