# Generated by Django 5.0.4 on 2024-05-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_agentcontactform_assigned_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcontactform',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
