# Generated by Django 5.0.6 on 2024-05-31 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_rename_phone_agentcontactform_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(models.F('user'), name='unique-agent'),
        ),
    ]
