# Generated by Django 5.0.6 on 2024-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='property_url',
            field=models.CharField(default='state=Tennessee&city=Nashville-Davidson&address=4607B Illinois Ave&zip=37209&id=0/&lat=36.1575202&long=-86.8431704', max_length=1000),
            preserve_default=False,
        ),
    ]
