# Generated by Django 5.0.6 on 2024-06-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('image', models.ImageField(default='property_images/default/shrek.webp', upload_to='property_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cap_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('beds', models.IntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sq_ft', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedproperty',
            constraint=models.UniqueConstraint(models.F('profile'), models.F('property_id'), name='profile-property_id'),
        ),
    ]
