# Generated by Django 5.0.4 on 2024-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_savedproperty_profile_delete_comment_and_more'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedproperty',
            constraint=models.UniqueConstraint(models.F('profile'), models.F('property_id'), name='profile-property_id'),
        ),
    ]
