# Generated by Django 5.0.4 on 2024-04-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='text',
        ),
    ]
