# Generated by Django 5.0.4 on 2024-05-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_savedproperty_profile_delete_comment_and_more'),
        ('property', '0005_commentlike_commentlike_profile_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.reply')),
            ],
        ),
        migrations.AddConstraint(
            model_name='replylike',
            constraint=models.UniqueConstraint(models.F('profile'), models.F('reply'), name='profile-reply'),
        ),
    ]
