# Generated by Django 5.0.4 on 2024-05-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_savedproperty_profile_delete_comment_and_more'),
        ('property', '0006_replylike_replylike_profile_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Comment', 'Comment'), ('Reply', 'Reply')], max_length=10)),
                ('object_id', models.IntegerField()),
                ('reported_text', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cause', models.CharField(choices=[('Spam', 'Spam'), ('Harrassment', 'Harrassment'), ('Threatening Violence', 'Threatening Violence'), ('Hate Speech', 'Hate Speech'), ('Impersonation', 'Impersonation'), ('Prohibited Transaction', 'Prohibited Transaction'), ('Other', 'Other')], max_length=40)),
                ('resolved', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, choices=[('Delete', 'Delete'), ('Ignore', 'Ignore'), ('TempCommentBan', 'TempCommentBan'), ('CommentBan', 'CommentBan')], max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
        ),
    ]
