# Generated by Django 5.0.4 on 2024-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_reportform'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='property_address',
            field=models.CharField(default='5663 Dunridge drive Pace FL 32571', max_length=250),
            preserve_default=False,
        ),
    ]
