# Generated by Django 5.0.4 on 2024-05-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_comment_property_address'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reply',
        #     name='comment',
        # ),
        # migrations.RemoveField(
        #     model_name='commentlike',
        #     name='comment',
        # ),
        # migrations.RemoveField(
        #     model_name='commentlike',
        #     name='profile',
        # ),
        # migrations.RemoveField(
        #     model_name='reply',
        #     name='profile',
        # ),
        # migrations.RemoveField(
        #     model_name='replylike',
        #     name='reply',
        # ),
        # migrations.RemoveField(
        #     model_name='replylike',
        #     name='profile',
        # ),
        # migrations.RemoveField(
        #     model_name='reportform',
        #     name='profile',
        # ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='ReplyLike',
        ),
        migrations.DeleteModel(
            name='ReportForm',
        ),
    ]
