# Generated by Django 5.0.4 on 2024-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_reply_comment_remove_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='beds',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='cap_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
