# Generated by Django 5.0.4 on 2024-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_savedproperty_baths_savedproperty_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='sa_ft',
            field=models.IntegerField(default=1300),
            preserve_default=False,
        ),
    ]
