# Generated by Django 5.0.4 on 2024-05-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_savedproperty_sa_ft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproperty',
            old_name='sa_ft',
            new_name='sq_ft',
        ),
    ]
