# Generated by Django 5.0.4 on 2024-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_rename_sa_ft_savedproperty_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='image',
            field=models.ImageField(default='property_images/default/shrek.webp', upload_to='property_images/'),
        ),
    ]
