# Generated by Django 5.0.4 on 2024-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_savedproperty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='city',
            field=models.CharField(default='Pensacola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='state',
            field=models.CharField(default='FL', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='zip',
            field=models.IntegerField(default=32571),
            preserve_default=False,
        ),
    ]
