# Generated by Django 5.0.6 on 2024-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_savedproperty_city_savedproperty_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='cap_rate',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
