# Generated by Django 5.0.6 on 2024-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link',
            new_name='link_alt_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='link_href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
