# Generated by Django 5.0.6 on 2024-06-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_link_notification_link_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadNotification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.notification',),
        ),
    ]
